import crypto from "node:crypto";

function b64(value){return Buffer.from(value).toString("base64url");}
export function sheetsConfigured(){return Boolean(process.env.GOOGLE_SHEETS_CLIENT_EMAIL&&process.env.GOOGLE_SHEETS_PRIVATE_KEY&&process.env.GOOGLE_SHEETS_SPREADSHEET_ID);}
function settings(){if(!sheetsConfigured())throw new Error("CONFIG");return {clientEmail:process.env.GOOGLE_SHEETS_CLIENT_EMAIL,privateKey:process.env.GOOGLE_SHEETS_PRIVATE_KEY.replace(/\\n/g,"\n"),spreadsheetId:process.env.GOOGLE_SHEETS_SPREADSHEET_ID,sheetName:process.env.GOOGLE_SHEETS_REGISTER_SHEET_NAME||"Kayitlar"};}
async function accessToken(clientEmail,privateKey){const now=Math.floor(Date.now()/1000),header=b64(JSON.stringify({alg:"RS256",typ:"JWT"})),claim=b64(JSON.stringify({iss:clientEmail,scope:"https://www.googleapis.com/auth/spreadsheets",aud:"https://oauth2.googleapis.com/token",iat:now,exp:now+3600})),unsigned=`${header}.${claim}`,signature=crypto.sign("RSA-SHA256",Buffer.from(unsigned),privateKey).toString("base64url");const response=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"urn:ietf:params:oauth:grant-type:jwt-bearer",assertion:`${unsigned}.${signature}`})});if(!response.ok)throw new Error("GOOGLE_AUTH");return (await response.json()).access_token;}
async function context(){const cfg=settings(),token=await accessToken(cfg.clientEmail,cfg.privateKey),range=`'${cfg.sheetName.replace(/'/g,"''")}'!A:J`;return {...cfg,range,headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"}};}
export async function getRows(){const ctx=await context();const response=await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(ctx.spreadsheetId)}/values/${encodeURIComponent(ctx.range)}?majorDimension=ROWS`,{headers:ctx.headers});if(!response.ok)throw new Error("SHEET_READ");return {rows:(await response.json()).values||[],ctx};}
export async function appendRows(ctx,values){const response=await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(ctx.spreadsheetId)}/values/${encodeURIComponent(ctx.range)}:append?valueInputOption=RAW&insertDataOption=INSERT_ROWS`,{method:"POST",headers:ctx.headers,body:JSON.stringify({values})});if(!response.ok)throw new Error("SHEET_WRITE");}
export function findUser(rows,email){return rows.find((row,index)=>index>0&&String(row[5]||"").trim().toLowerCase()===email)||null;}
