name: Automated Test Generation

on:
  repository_dispatch:
    types:
      - generate_test

jobs:
  generate-test:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu çek
        uses: actions/checkout@v4

      - name: Metadata bilgilerini göster
        run: |
          echo "SINIF: ${{ github.event.client_payload.sinif }}"
          echo "DERS: ${{ github.event.client_payload.ders }}"
          echo "KONU: ${{ github.event.client_payload.konu }}"
          echo "TEST NO: ${{ github.event.client_payload.testNo }}"
          echo "ZORLUK: ${{ github.event.client_payload.zorluk }}"

      - name: Tests klasörü oluştur
        run: mkdir -p tests

      - name: HTML test dosyası oluştur
        run: |
          FILE_NAME="${{ github.event.client_payload.ders }}-${{ github.event.client_payload.konu }}-test-${{ github.event.client_payload.testNo }}.html"

          echo "<!DOCTYPE html>
          <html>
          <head>
            <meta charset='UTF-8'>
            <title>TestÇöz</title>
          </head>
          <body style='font-family: Arial; padding:40px'>
            <h1>Test başarıyla oluşturuldu 🚀</h1>

            <p>Sınıf: ${{ github.event.client_payload.sinif }}</p>
            <p>Ders: ${{ github.event.client_payload.ders }}</p>
            <p>Konu: ${{ github.event.client_payload.konu }}</p>
            <p>Test: ${{ github.event.client_payload.testNo }}</p>
            <p>Zorluk: ${{ github.event.client_payload.zorluk }}</p>
          </body>
          </html>" > tests/$FILE_NAME

      - name: Git ayarla
        run: |
          git config user.name "testcoz-bot"
          git config user.email "bot@testcoz.pro"

      - name: Commit oluştur
        run: |
          git add .
          git commit -m "Yeni otomatik test oluşturuldu" || echo "Değişiklik yok"

      - name: GitHub push
        run: |
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ secrets.GH_OWNER }}/${{ secrets.GH_REPO }}.git HEAD:main
